name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/prepare

      - run: pnpm exec prettier --check .
      - run: pnpm exec eslint .
      - run: pnpm -r typecheck
      - run: pnpm exec vitest run
